### ISSUE TITLE
Works... but tokens get disabled

### ISSUE THREAD

**Issue by UnwizzabIe** [Hattorius/discord-account-generator#3]
Tokens get disabled after phone verification, even with residential proxy usage.

**Comment by Hattorius** [comment]
Didn't do that for me, probably a Discord patch

**Comment by UnwizzabIe** [comment]
> Didn't do that for me, probably a Discord patch

Are you still able to generate with no issue? It may be a problem on my end.

**Comment by ItsCEED** [comment]
This should work, the captcha service might get fucked as they can't change much in order to patch gen.

**Comment by KeparYTbcc** [comment]
![image](https://user-images.githubusercontent.com/67996155/147896250-d3416c4d-b840-4070-8e01-cf339c6f189d.png)

**Comment by KeparYTbcc** [comment]
All tokens are phone verified , ALL DISABLED

**Comment by Hattorius** [comment]
Just tested it
![Screenshot_20220103_155925](https://user-images.githubusercontent.com/54858358/147945751-97e82213-7411-44c2-9faf-d8bcbcded33c.png)

Got no problem creating accounts at all. It might be because of the proxies you guys are using.
