### ISSUE TITLE
Tokens are not saving.

### ISSUE THREAD

**Issue by xxopenxx** [Hattorius/discord-account-generator#6]
Hi! Im using third example, and my tokens are not saving in Tokens.txt

**Comment by DeepakPaswan12** [comment]
can you help me?

**Comment by Hattorius** [comment]
> Hi! Im using third example, and my tokens are not saving in Tokens.txt

I did not test the examples (except the first one). I just wrote them down in the readme to give an idea on what you can do with this library.
